name = "fetchbook-org"
main = "src/index.tsx"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "fetchbook-db"
database_id = "12a9989b-1b21-4c09-a235-5136a93310a0"

[vars]
GITHUB_CLIENT_ID = "Ov23liXO9otdrecs5HaH"
